<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	<Version>1.1.2</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    <ApplicationName>HTPC</ApplicationName>
    <AssemblyName>HTPC</AssemblyName>
    
    <StartupObject>HTPC.Program</StartupObject>
    <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
    <TieredCompilation>true</TieredCompilation>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>NU1903;CS4014</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
     <None Update="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="mpv-2.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Shaders\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>